name: Build LaTeX documents
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile Assignment 3
        uses: xu-cheng/latex-action@master
        with:
          working_directory: "./Assignment 3"
          root_file: "Assignment 3.tex"
          extra_packages: "karnaugh-map enumitem xstring"
      - name: Compile Assignment 4
        uses: xu-cheng/latex-action@master
        with:
          working_directory: "./Assignment 4"
          root_file: "Assignment 4.tex"
          extra_packages: "enumitem xstring"
      - name: Create Release
        uses: ncipollo/release-action@v1
        with: 
          artifacts: "*/*.pdf"
          artifactContentType: pdf
          token: ${{ secrets.GITHUB_TOKEN }}