name: Build LaTeX documents
on:
  push:
    branches:
      - master
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile Assignment 3
        uses: xu-cheng/latex-action@master
        with:
          working_directory: "./Assignment_3"
          root_file: "Assignment_3.tex"
          extra_packages: "karnaugh-map enumitem xstring"
      - name: Compile Assignment 4
        uses: xu-cheng/latex-action@master
        with:
          working_directory: "./Assignment_4"
          root_file: "Assignment_4.tex"
          extra_packages: "enumitem xstring"
      - name: Set enviroment for github-release
        run: |
          dt=$(date '+%d/%m/%Y %H:%M:%S')
          echo ::set-env name=RELEASE_TAG::"$dt"
      - name: Create Release
        uses: meeDamian/github-release@1.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          allow_override: true
          gzip: false
          tag: $dt
          files: >
            "Assignment_3/Assignment_3.pdf"
            "Assignment_4/Assignment_4.pdf"